# Custom Language File for Launcher Customizer

[ejs.app]
title = "Wolf Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/boringwolf/WolfLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/gjqPdW9TEr"

[ejs.settings]
sourceGithubLink = "https://github.com/boringwolf/WolfLauncher"
supportLink = "https://github.com/boringwolf/WolfLauncher/issues"

[ejs.welcome]
welcomeHeader = "歡迎來到 Wolf SMP (暫定)"
welcomeDescription = "我們的伺服器是一個獨特的SMP（生存多人）伺服器，我們的核心理念是在Minecraft中創建一個結合了Fivem角色扮演元素的優質RP（角色扮演）環境。這種方式與以往傳統的Minecraft遊玩體驗截然不同，我們致力於提供一個豐富多彩、互動性強的遊戲世界，讓玩家能夠深入角色，創建和參與自己的故事。"
welcomeDescCTA = "您只需幾步之遙，便可踏入 Wolf SMP。"
